### ISSUE TITLE
iPhone X size issue

### ISSUE THREAD

**Issue by seung1231** [bambuser/react-native-bambuser-player#10]
Hi, I am reopening the issue. I've tried to use View other than SafeAreaView, but the archived videos are still cut off at the very top and bottom of the screen. The only style I applied to the View was flex: 1. This issue only appears on iPhones with bigger screens.

**Comment by peterlofquist** [comment]
Could you provide some sample code to make it easy for me to reproduce?

**Comment by seung1231** [comment]
The code roughly looks like

<View style={{ flex: 1 }}>
  <RNBambuserPlayer
    style={styles.cameraView}
    ...
  />
  <View>
  ...other functions on top of video
  </View>
</View>

cameraView: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },

We want the video on the background with other functions on top of the video, but for iPhoneX and bigger, we get black spaces on the top and bottom.

**Comment by peterlofquist** [comment]
Ah right. So you want the entire background to be used up by the video component?

Is this the outcome you wish to achieve? (Screenshot below)
![Simulator Screen Shot - iPhone X - 2019-08-08 at 09 41 43](https://user-images.githubusercontent.com/2319341/62684596-480aba00-b9c1-11e9-9add-e4220753be31.png)

But you are currently getting this? (Screenshot below)
![Simulator Screen Shot - iPhone X - 2019-08-08 at 09 42 33](https://user-images.githubusercontent.com/2319341/62684664-7092b400-b9c1-11e9-827a-b365df1ea2a6.png)

If that's the case the I would add the property `videoScaleMode` with the value of `RNBambuserPlayer.VIDEO_SCALE_MODE.ASPECT_FILL` to scale and fill the entire player view regardless of device screen size.

```
  ...
  render() {
    return (
      <View style={{
        flex: 1,
        backgroundColor: 'black',
      }}>
        <RNBambuserPlayer style={{
          flex: 1,
        }}
        applicationId='yourApplicationId'
        resourceUri='yourSignedResourceUri'
        ref={ref => this.player = ref}
        videoScaleMode={RNBambuserPlayer.VIDEO_SCALE_MODE.ASPECT_FILL}
        onReady={() => {
          this.player.play();
        }} />
      </View>
    );
  }
  ...
```

**Comment by seung1231** [comment]
Thank you! Worked great. Even works on SafeAreaView.
