### ISSUE TITLE
Could not build module 'UIKit' - xcode 10 build failing

### ISSUE THREAD

**Issue by dineshmatta** [bambuser/react-native-bambuser-player#11]
I tried multiple times after cleaning, removing derived data, but still getting the below error:

While building module 'UIKit' imported from /Users/***/node_modules/react-native-bambuser-player/ios/BambuserPlayerView.h:5:

I followed all steps mentioned in the documentation for bambuserbroadcaster module as well as for bambuserplayer module.

I am using react-native with Expokit and using Xcode 10 to build the ios project

Attached the screenshot of the errors which I am getting

![image](https://user-images.githubusercontent.com/1083007/63318057-178d1f00-c2e3-11e9-91eb-6ac8b2480a72.png)

**Comment by dineshmatta** [comment]
Hey @peterlofquist 

Would you mind checking the above error which I am getting for ios build, we are blocked because of these issues(raised a different issue in react-native-bambuser-broadcaster package). Thanks

**Comment by peterlofquist** [comment]
I am not able to reproduce this error. Do you still get this error if you build a project without ExpoKit?

Could you provide a test project, sample code or any additional information which helps us reproduce this issue?

**Comment by peterlofquist** [comment]
Thank you for the patience. We've now updated our React Native component to play nicely along with React Native 0.60+. Please follow the updated README.md for this project, it'll point you in the correct direction.

Please open again if you still have issues.

**Comment by dineshmatta** [comment]
Thanks @peterlofquist for this update, hoepfully this update will work with our react-native 0.59.10 version too?

**Comment by peterlofquist** [comment]
Make sure to install our iOS SDK via CocoaPods and I believe there won't be any problems.

**Comment by peterlofquist** [comment]
And if the issue persists I suggest you either upgrade to a newer version of React Native, or you simply copy the iOS specific files from this repository to your main React Native project. By copying the files into your main React Native project Xcode should not have any issues with finding the proper pathing to the files.

**Comment by dineshmatta** [comment]
Thanks @peterlofquist for this info, I tried with my react-native version 0.59.10 by installing Bambuser IOS sdk through CocoaPods but still getting below error

![image](https://user-images.githubusercontent.com/1083007/64056956-533aab00-cb65-11e9-9d6b-097d2bb1ee1b.png)


Now I guess I only have an option of trying with react-native version 0.60, I will see if I can upgrade to react native version 0.60 as it requries lot of changes to our exsting packages

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

Looks like I cannot upgrade my app to react-native version 0.60 since there are lot of breaking changes with my existing packages, So now I am continuing with my react-native version 0.59.10

I am getting below error after restarting my Xcode and cleaning cache and derived data folder

![image](https://user-images.githubusercontent.com/1083007/64070053-6b263380-cc26-11e9-8211-8c5afbaa1566.png)

Do you have any idea about this error, I installed the ios-sdk using cocoapods, so build is passing, but when I am trying to use this react-native component in my app then it crashes with the above error

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

So after trying for multiple times with react-native version 0.59.10 and your sdk version 0.9.22 and 0.9.23 (installed manually/Cocoapods) but still getting the first error mentioned in this thread


So looks like there are no clear steps for react-native version below 0.60

**Comment by peterlofquist** [comment]
@dineshmatta We currently only support the latest React Native version, if you wish to use an older version of React Native, in your case `0.59.10` I'd suggest you do the following:

1) Install libbambuser via Cocoapods.
2) Run `yarn add react-native-bambuser-player`.
3) Run `react-native link react-native-bambuser-player` (This doesn't do anything of value for your iOS setup in this case, but it should link the files properly for the Android part of your project).
4) Navigate to `[your-project]/node_modules/react-native-bambuser-player/ios`, drag and drop the `*.h/.m` files from named directory into your React Native Xcode project. Check the box `Copy items if needed` and accept.

Your Xcode project should now look something like this:
<img width="264" alt="Screenshot 2019-09-02 at 09 42 02" src="https://user-images.githubusercontent.com/2319341/64098225-9adc5500-cd66-11e9-932a-a997a7b4d191.png">

After these steps the React Native UIManager should be able to find all the files it needs to run properly.

Please note that by using `react-native-bambuser-player` this way you have to manually update this projects iOS files in the future.

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

Thank you so much for detail instructions, with the help of your instructions I am now able to use this component in my react-native v0.59.10, also I tested in react-native v0.60.5 there also it is working seamlessly.

Thanks once again for these instructions
