### ISSUE TITLE
this.myPlayerRef.seekTo(position); stating video from 0th position

### ISSUE THREAD

**Issue by vilaskumkar** [bambuser/react-native-bambuser-player#14]
```
  onProgressUpdate = (live, currentPosition, duration) => {
    this.setState({
      currentPositionOfVideo: Number(currentPosition)
    }, () => {console.log(" this.state.currentPositionOfVideo >>>>", this.state.currentPositionOfVideo);});
  };
```
```
  forwardOrRevind(value) {
    const currentPosition = this.state.currentPositionOfVideo;
    const forwardOrRevindBy = 10;
    const forwardPosition = currentPosition + forwardOrRevindBy;
    const revindPosition = currentPosition - forwardOrRevindBy;
    if (value) {
      this.myPlayerRef.seekTo(forwardPosition);
    } else {
      this.myPlayerRef.seekTo(revindPosition);
    }
  };
```

I'm calling the `forwardOrRevind()` function onPress of button, but video player starts playing video from 0th position.

**Comment by dineshmatta** [comment]
Hey @peterlofquist,

Can you please check the above issue, we are facing issue in implementing Fast forward and Rewind feature as seekTo function always default/starts from 0.

Thanks

**Comment by peterlofquist** [comment]
Is this a iOS or Android specific issue?

**Comment by dineshmatta** [comment]
We tried this in IOS simulator, not yet tried in android

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

I asked one of my dev, he tried this in Android as well and was getting the same issue

**Comment by dineshmatta** [comment]
Hey @peterlofquist 

Do you guys have any update on this issue as it is blocked from last week.

Thanks

**Comment by peterlofquist** [comment]
This issue should be resolved here: https://github.com/bambuser/react-native-bambuser-player/commit/c62d5401709434bd77a32ce3dc0cfa803495b5fe

Please reopen this issue if you still experience problems after updating to 0.0.14, happy coding! :-)

**Comment by dineshmatta** [comment]
Thank you so much @peterlofquist, I will test this and will update you.
