### ISSUE TITLE
IgnoreSilentSwitch set to ignore does not work

### ISSUE THREAD

**Issue by voslartomas** [bambuser/react-native-bambuser-player#18]
Hello, trying out to set IgnoreSilentSwitch to be able to ignore silent mode, but does not work, when I open app in silent mode, audio is not playing.

**Comment by peterlofquist** [comment]
Did you experience this issue on iOS or Android? I realize that this feature is a bit misleading right now and is currently only implemented for iOS, I'll patch the documentation shortly.

**Comment by voslartomas** [comment]
This is on iOS.

**Comment by felippepuhle** [comment]
`ignoreSilentSwitch={RNBambuserPlayer.IGNORE_SILENT_SWITCH.IGNORE}` is working here

**Comment by karanpratapsingh** [comment]
I can confirm, crashes on ios with RN 0.62

**Comment by peterlofquist** [comment]
@karanpratapsingh 
> I can confirm, crashes on ios with RN 0.62

Can you provide any crash log or sample code where you can reproduce this issue? 


@voslartomas 
Can you provide any additional information regarding what device you are testing on and if possible some sample code where you can reproduce this issue where you are experiencing? I can't reproduce a crash or any indication that it's not working as intended here on a physical iOS device.

**Comment by voslartomas** [comment]
It seems working, I have used wrong value.
