### ISSUE TITLE
<RNBambuserPlayer > renders black screen 

### ISSUE THREAD

**Issue by jhltom** [bambuser/react-native-bambuser-player#2]
I followed all the instructions in the installation documentation but my 'RNBambuserPlayer' renders a black screen without playing the video. This is a simplified version of my code:

![Screen Shot 2019-05-01 at 10 23 52 PM](https://user-images.githubusercontent.com/43786249/57018854-da335180-6c5f-11e9-823b-3e89d337929a.png)

What might be the problem?  By the way, I have no problems with 'RNBambuserBroadcaster'.

**Comment by peterlofquist** [comment]
By just giving a quick glance on the code provided above I'd say you try to play the video before the player reference is ready to accept the `play()` command.

Can you try to implement the onReady callback on the RNBambuserPlayer component and call the `this.myPlayerRef.play()` inside of the callback, I believe that would do the trick, granted that the resourceUri you provide is available. :-)
```
onReady: function()
// Callback when the player is available and can accept inputs, such as playing a video.
```

**Comment by jhltom** [comment]
Could you provide an example of how the onReady callback prop can be implemented on the RNBambuserPlayer component? I tried the following but didn't work:

```
    ready = async () => {
        this.myPlayerRef.play();
    }
    render() {
        const rURI = this.props.navigation.getParam('resourceUri');
        //console.warn(rURI);
        return (
            <View style={styles.container}>
                <RNBambuserPlayer
                    style={styles.cameraView}
                    ref={ref => { this.myPlayerRef = ref }}
                    applicationId={'UblS95aRt8bDbDU2lIhplg'}
                    resourceUri={rURI}
                    onReady={async () =>  await this.ready()}
                />
            </View>
        )
    }
```

**Comment by jhltom** [comment]
Could you provide an example of how the onReady callback prop can be implemented on the RNBambuserPlayer component? I tried the following but didn't work:

```
    ready = async () => {
        this.myPlayerRef.play();
    }
    render() {
        const rURI = this.props.navigation.getParam('resourceUri');
        //console.warn(rURI);
        return (
            <View style={styles.container}>
                <RNBambuserPlayer
                    style={styles.cameraView}
                    ref={ref => { this.myPlayerRef = ref }}
                    applicationId={'myid'}
                    resourceUri={rURI}
                    onReady={async () =>  await this.ready()}
                />
            </View>
        )
    }
```

**Comment by peterlofquist** [comment]
There did indeed seem to be an issue with this React Native component together with the latest version of the iOS SDK(0.9.22) which explains why the playback did not work.

I updated the NPM package with a new version(0.0.11) of this component which should work well with our latest iOS libbambuser player SDK(0.9.22). By running `$ yarn add react-native-bambuser-player`(or alike with your favorite package manager) you should be able to download the latest `react-native-bambuser-player` node module.

This snippet below should be the minimal amount of code you need in order to automatically load and play a resourceUri.
```
render() {
    return (
      <RNBambuserPlayer style={{
          flex: 1
        }}
        applicationId='your-application-id'
        resourceUri='https://cdn.bambuser.net/broadcasts/ec968ec1-2fd9-f8f3-4f0a-d8e19dccd739?da_signature_method=HMAC-SHA256&da_id=432cebc3-4fde-5cbb-e82f-88b013140ebe&da_timestamp=1456740399&da_static=1&da_ttl=0&da_signature=8e0f9b98397c53e58f9d06d362e1de3cb6b69494e5d0e441307dfc9f854a2479'
        ref={ref => this.playerRef = ref}
        onReady={() => {
          this.playerRef.play();
        }} />
    );
  }
```

Please report back if this solves your issues :-)

**Comment by jhltom** [comment]
This solved the issue, thank you very much!
