### ISSUE TITLE
Enabling sound in silent mode (IOS) 

### ISSUE THREAD

**Issue by jhltom** [bambuser/react-native-bambuser-player#8]
Is there a way to enable sound when playing the video in silent/vibration mode (iOS)? If not, would you guys consider including this feature in the SDK?

**Comment by peterlofquist** [comment]
Currently there's no option to enable this feature in our own Player SDK. There is however the possibility for you to implement this kind of functionality for your own app, you can read more about it here in this Stackoverflow thread: https://stackoverflow.com/questions/35289918/play-audio-when-device-in-silent-mode-ios-swift

**Comment by felippepuhle** [comment]
@peterlofquist can't we add this on bambuser sdk? I don't want to create a bridge just to handle this kind of situation.

It should be simple, just doing something like this on `play` method:

https://github.com/react-native-community/react-native-video/blob/master/ios/Video/RCTVideo.m#L866

**Comment by peterlofquist** [comment]
Thank you for the suggestion @felippepuhle. I don't have the time to implement this just now, but you are more than welcome to create a pull request in order to provide this functionality.

Otherwise I'll look at this feature request when time presents itself! 🙂

**Comment by felippepuhle** [comment]
Oh, that's awesome! but I don't think I have access to the IOS SDK itself, should we handle this only for the react native SDK?

I can send a PR later on

Thanks!
