### ISSUE TITLE
this.myPlayerRef.stop(); not working on componentWillUnmount()

### ISSUE THREAD

**Issue by balu3083** [bambuser/react-native-bambuser-player#9]
Hi ,
I am trying to stop player when user leave the page. I called this.myPlayerRef.stop() method on 
componentWillUnmount(). When I try this I am getting black screen can't able to see any videos. My requirment is I want to stop player When I exit the page by clicking backbutton or close the app by clicking home button of the device

Thanks
Balakrishnan

**Comment by peterlofquist** [comment]
> I called this.myPlayerRef.stop() method on
componentWillUnmount(). When I try this I am getting black screen can't able to see any videos.

This sounds like it's working as intended. You call stop on the player and the video is then stopped. If you want to play other videos after you called stop you should set up a new player, not reuse the old one. One way to ensure that you initiate a new player in React Native is to set a key property for the RNBambuserPlayer component.
